name: Build & Push Grammar Hero

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- API --------
      - name: Build API image
        run: |
          docker build \
            -t 3ahxut123nurbek/grammar-hero-api:latest \
            -t 3ahxut123nurbek/grammar-hero-api:${{ github.sha }} \
            -f docker/server.Dockerfile \
            apps/server

      # -------- WEB --------
      - name: Build WEB image
        run: |
          docker build \
            -t 3ahxut123nurbek/grammar-hero-web:latest \
            -t 3ahxut123nurbek/grammar-hero-web:${{ github.sha }} \
            -f docker/web.Dockerfile \
            apps/web

      - name: Push images
        run: |
          docker push 3ahxut123nurbek/grammar-hero-api:latest
          docker push 3ahxut123nurbek/grammar-hero-api:${{ github.sha }}
          docker push 3ahxut123nurbek/grammar-hero-web:latest
          docker push 3ahxut123nurbek/grammar-hero-web:${{ github.sha }}